version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - '.env'
    volumes:
      - ./data:/data:Z
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backnet
  backend:
    build: backend
    restart: always
    env_file:
      - '.env'
    volumes:
      - ./backend/app:/app:Z
    ports:
      - "8000:8000"
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
  proxy:
    build: proxy
    restart: always
    ports:
      - "8001:80"
    depends_on: 
      - backend
    networks:
      - backnet
      - frontnet

networks:
  backnet:
  frontnet: